export const scheduleData = [
  {
    day: 'Day 0 – CJO Day',
    date: 'July 10, 2025 (GMT+4)',
    activities: [
      { time: '10:30–11:30', title: 'Officials Registration', location: 'Globus Centre' },
      { time: '11:30–12:00', title: 'General Teambuilding', location: 'Globus Centre' },
      { time: '12:00–12:30', title: 'Safe Talk', location: 'Globus Centre' },
      { time: '12:30–13:30', title: 'Officials Training I', location: 'Globus Centre' },
      { time: '13:30–14:00', title: 'Coffee Break', location: 'Cafeteria' },
      { time: '14:00–15:00', title: 'Officials Training II', location: 'Globus Centre' },
      { time: '15:00–16:00', title: 'Lunch Break', location: 'Dining Area' },
      { time: '16:00–17:30', title: 'Officials Training III', location: 'Globus Centre' },
      { time: '17:30–18:00', title: 'Coffee Break', location: 'Cafeteria' },
      { time: '18:00–19:00', title: 'Officials Training IV', location: 'Globus Centre' },
      { time: '19:00', title: 'Officials Dinner', location: 'Globus Centre' },
    ],
  },
  {
    day: 'Day 1 – Teambuilding Day',
    date: 'July 12, 2025 (GMT+4)',
    activities: [
      { time: '09:30–10:30', title: 'Trainees Arrive', location: 'Campus Entrance' },
      { time: '10:30–12:30', title: 'Trip to Gobuland', location: 'Departure Point' },
      { time: '12:30–14:00', title: 'General Teambuilding + Opening Ceremony', location: 'Gobuland' },
      { time: '14:00–15:00', title: 'Lunch Break', location: 'Restaurant' },
      { time: '15:00–17:00', title: 'Training I', location: 'Gobuland' },
      { time: '17:00–17:30', title: 'Coffee Break', location: 'Gobuland' },
      { time: '17:30–18:30', title: 'Training II', location: 'Gobuland' },
      { time: '18:30–19:30', title: 'Evening Activity', location: 'Gobuland' },
      { time: '19:30–20:30', title: 'Dinner', location: 'Restaurant' },
    ],
  },
  {
    day: 'Day 2 – Training Day',
    date: 'July 13, 2025 (GMT+4)',
    activities: [
      { time: '08:00–08:40', title: 'Breakfast', location: 'Dining Area' },
      { time: '08:40–09:00', title: 'Meditation', location: 'Gobuland' },
      { time: '09:00–11:00', title: 'Training III', location: 'Gobuland' },
      { time: '11:00–11:30', title: 'Coffee Break', location: 'Gobuland' },
      { time: '11:30–13:30', title: 'Training IV', location: 'Gobuland' },
      { time: '13:30–14:30', title: 'Lunch Break', location: 'Restaurant' },
      { time: '14:30–15:30', title: 'Training V', location: 'Gobuland' },
      { time: '15:30–16:00', title: 'Coffee Break', location: 'Gobuland' },
      { time: '16:00–18:00', title: 'Training VI', location: 'Gobuland' },
      { time: '18:00–19:00', title: 'Evening Activity', location: 'Gobuland' },
      { time: '19:00–20:00', title: 'Dinner', location: 'Restaurant' },
      { time: '20:00–22:00', title: 'Closing Ceremony', location: 'Gobuland' },
    ],
  },
  {
    day: 'Day 3 – Training Day',
    date: 'July 14, 2025 (GMT+4)',
    activities: [
      { time: '08:00–08:30', title: 'Morning Activity', location: 'Gobuland' },
      { time: '08:30–09:30', title: 'Breakfast', location: 'Dining Area' },
      { time: '09:30–10:30', title: 'Training VII', location: 'Gobuland' },
      { time: '10:30–11:30', title: 'Packing Up', location: 'Gobuland' },
      { time: '11:30–14:00', title: 'Trip to Baku', location: 'Departure Point' },
    ],
  },
]